### ISSUE TITLE
Proposal for Better System

### ISSUE THREAD

**Issue by Rushmead** [Geforce132/Beacon#1]
Hello,

Its Rushmead here and i have a Proposal for a Better System to Get each Mods Information. I Propose that We use MySQL Databases instead (I don't mind Hosting) and then "i" or "we" Would create a Admin Panel for this Database allowing us and possibly mod authors to add there mods and possibly create a API so mod authors can automatically add it when a new Version is released. This is a much Easier system than Using PR's and txt files. 

I Hope you take this into Consideration.
Also if you require more Infomation or want to ask more Questions feel free to Down below
Thanks
Rushmead

**Comment by Geforce132** [comment]
Well, just this morning, I've made it so where Beacon will download the latest version of the modList.txt file in this repository whenever it's lauched, so I don't have to keep re-releasing new versions of Beacon with the updated list. Most modders have GitHub accounts, and they will only have to add one line of text to the list to add their mod. I think we'll be good for now, but if the .txt file starts getting to big, I might have to use a MySQL database. Ideas?

**Comment by Rushmead** [comment]
Personly I think at this moment in time this will be a boost for this mod.

**Comment by VikeStep** [comment]
Just gonna pop in and say that the way you are currently doing it is a lot of hassle and means that you need to update modlist.txt every single time a mod has an update. Have you thought about maybe looking into checking versions from NotEnoughMods?

The only reason I am not adding my mod to this now is because it requires me to update the modlist.txt file each time I would release an update.

Another possible idea is to send a packet to the server and have mod devs add a simple class to their mod that returns the download link to the mod if the versions don't match. However, not sure how feasible that is.

**Comment by Geforce132** [comment]
Rushmead:

Hey, why don't we try that MySQL database idea you talked about? We can see how well it works out.

VikeStep:
Yeah, I'm trying to work on a better system. I was thinking about maybe using IRC to help in some way...?

**Comment by Geforce132** [comment]
Well, I'm totally changing how Beacon works. Beacon now find downloads directly from minecraft.curseforge.com, so no more adding new updates to the modList.txt file every time you release an update. I guess I can close this issue now.
